spring : 
  datasource : 
    url : jdbc:h2:tcp://localhost/~/DEV/h2_database_file/querydsl
    username : sa
    password : 
    driver-class-name : org.h2.Driver
    
  jpa : 
    hibernate : 
      ddl-auto : create
    properties :
      hibernate : 
#        show_sql : tru
        format_sql : true
        use_sql_comments : true # 실행되는 JPQL 로그
        
logging.level : 
  org.hibernate.SQL : debug
#  org.hibernate.type : trace